use rand::RngCore;
use std::{env, fs, path::PathBuf};

fn obfuscate(input: &[u8], key: &[u8; 32]) -> Vec<u8> {
    input
        .iter()
        .enumerate()
        .map(|(idx, byte)| {
            let salt = ((idx as u64).wrapping_mul(31).wrapping_add(17) & 0xff) as u8;
            byte ^ key[idx % key.len()] ^ salt
        })
        .collect()
}

fn to_rust_u8_array(bytes: &[u8]) -> String {
    let mut out = String::from("[");
    for (idx, b) in bytes.iter().enumerate() {
        if idx > 0 {
            out.push_str(", ");
        }
        out.push_str(&b.to_string());
    }
    out.push(']');
    out
}

fn normalize_const_name(script_id: &str) -> String {
    let mut name = String::from("SCRIPT_");
    for ch in script_id.chars() {
        if ch.is_ascii_alphanumeric() {
            name.push(ch.to_ascii_uppercase());
        } else {
            name.push('_');
        }
    }
    name
}

fn main() {
    tauri_build::build();

    let manifest_dir =
        PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("Missing CARGO_MANIFEST_DIR"));
    let scripts_dir = manifest_dir.join("resources").join("scripts");
    println!("cargo:rerun-if-changed={}", scripts_dir.display());

    let mut key = [0_u8; 32];
    rand::thread_rng().fill_bytes(&mut key);

    let mut scripts: Vec<(String, String, Vec<u8>)> = Vec::new();
    let entries = fs::read_dir(&scripts_dir)
        .unwrap_or_else(|e| panic!("Failed to read scripts dir {}: {e}", scripts_dir.display()));

    for entry in entries {
        let path = entry.expect("Invalid scripts dir entry").path();
        let is_r_script = path
            .extension()
            .and_then(|ext| ext.to_str())
            .map(|ext| ext.eq_ignore_ascii_case("r"))
            .unwrap_or(false);
        if !is_r_script {
            continue;
        }

        println!("cargo:rerun-if-changed={}", path.display());
        let script_id = path
            .file_stem()
            .and_then(|name| name.to_str())
            .unwrap_or_else(|| panic!("Invalid script file name: {}", path.display()))
            .to_string();
        let const_name = normalize_const_name(&script_id);
        let plain = fs::read(&path)
            .unwrap_or_else(|e| panic!("Failed to read script {}: {e}", path.display()));
        scripts.push((script_id, const_name, obfuscate(&plain, &key)));
    }

    scripts.sort_by(|a, b| a.0.cmp(&b.0));
    if scripts.is_empty() {
        panic!("No R scripts found in {}", scripts_dir.display());
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("Missing OUT_DIR"));
    let out_file = out_dir.join("secure_scripts.rs");

    let mut generated = String::new();
    generated.push_str("// Generated by build.rs. Do not edit.\n");
    generated.push_str("pub const SCRIPT_KEY: [u8; 32] = ");
    generated.push_str(&to_rust_u8_array(&key));
    generated.push_str(";\n\n");

    for (_, const_name, blob) in &scripts {
        generated.push_str("static ");
        generated.push_str(const_name);
        generated.push_str(": &[u8] = &");
        generated.push_str(&to_rust_u8_array(blob));
        generated.push_str(";\n");
    }

    generated.push_str("\npub fn get_script_blob(id: &str) -> Option<&'static [u8]> {\n");
    generated.push_str("    match id {\n");
    for (script_id, const_name, _) in &scripts {
        generated.push_str("        \"");
        generated.push_str(script_id);
        generated.push_str("\" => Some(");
        generated.push_str(const_name);
        generated.push_str("),\n");
    }
    generated.push_str("        _ => None,\n");
    generated.push_str("    }\n");
    generated.push_str("}\n");

    fs::write(&out_file, generated)
        .unwrap_or_else(|e| panic!("Failed to write {}: {e}", out_file.display()));
}
